openapi: 3.0.3
info:
  title: Todo App - Tasks API
  description: Task CRUD endpoints for managing user tasks with JWT authentication
  version: 1.0.0
  contact:
    name: Todo Full-Stack Web Application

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.todo-app.example.com
    description: Production server

tags:
  - name: Tasks
    description: Task management endpoints (all require authentication)

security:
  - BearerAuth: []

paths:
  /api/{user_id}/tasks:
    parameters:
      - $ref: '#/components/parameters/UserIdPath'

    get:
      tags:
        - Tasks
      summary: Get all tasks for authenticated user
      description: Returns a list of all tasks belonging to the authenticated user. Tasks are sorted by creation date (newest first).
      operationId: getUserTasks
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
              examples:
                multipleTasks:
                  summary: User with multiple tasks
                  value:
                    - id: 123e4567-e89b-12d3-a456-426614174000
                      user_id: 550e8400-e29b-41d4-a716-446655440000
                      title: Buy groceries
                      description: Milk, eggs, bread
                      is_completed: false
                      created_at: '2026-02-06T10:30:00Z'
                      updated_at: '2026-02-06T10:30:00Z'
                    - id: 123e4567-e89b-12d3-a456-426614174001
                      user_id: 550e8400-e29b-41d4-a716-446655440000
                      title: Finish project report
                      description: null
                      is_completed: true
                      created_at: '2026-02-05T14:20:00Z'
                      updated_at: '2026-02-06T09:15:00Z'
                emptyList:
                  summary: User with no tasks
                  value: []
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      tags:
        - Tasks
      summary: Create a new task
      description: Creates a new task for the authenticated user. Title is required, description is optional.
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
            examples:
              withDescription:
                summary: Task with description
                value:
                  title: Buy groceries
                  description: Milk, eggs, bread
              withoutDescription:
                summary: Task without description
                value:
                  title: Call dentist
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              examples:
                createdTask:
                  summary: Newly created task
                  value:
                    id: 123e4567-e89b-12d3-a456-426614174000
                    user_id: 550e8400-e29b-41d4-a716-446655440000
                    title: Buy groceries
                    description: Milk, eggs, bread
                    is_completed: false
                    created_at: '2026-02-06T10:30:00Z'
                    updated_at: '2026-02-06T10:30:00Z'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/{user_id}/tasks/{task_id}:
    parameters:
      - $ref: '#/components/parameters/UserIdPath'
      - $ref: '#/components/parameters/TaskIdPath'

    get:
      tags:
        - Tasks
      summary: Get a specific task by ID
      description: Returns details of a single task. User can only access their own tasks.
      operationId: getTaskById
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              examples:
                taskDetails:
                  summary: Task with full details
                  value:
                    id: 123e4567-e89b-12d3-a456-426614174000
                    user_id: 550e8400-e29b-41d4-a716-446655440000
                    title: Buy groceries
                    description: Milk, eggs, bread
                    is_completed: false
                    created_at: '2026-02-06T10:30:00Z'
                    updated_at: '2026-02-06T10:30:00Z'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      tags:
        - Tasks
      summary: Update a task
      description: Updates title and/or description of an existing task. User can only update their own tasks.
      operationId: updateTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
            examples:
              updateBoth:
                summary: Update title and description
                value:
                  title: Buy groceries and supplies
                  description: Milk, eggs, bread, paper towels
              updateTitleOnly:
                summary: Update title only
                value:
                  title: Buy groceries and supplies
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              examples:
                updatedTask:
                  summary: Updated task
                  value:
                    id: 123e4567-e89b-12d3-a456-426614174000
                    user_id: 550e8400-e29b-41d4-a716-446655440000
                    title: Buy groceries and supplies
                    description: Milk, eggs, bread, paper towels
                    is_completed: false
                    created_at: '2026-02-06T10:30:00Z'
                    updated_at: '2026-02-06T11:45:00Z'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - Tasks
      summary: Delete a task
      description: Permanently deletes a task. User can only delete their own tasks.
      operationId: deleteTask
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/{user_id}/tasks/{task_id}/complete:
    parameters:
      - $ref: '#/components/parameters/UserIdPath'
      - $ref: '#/components/parameters/TaskIdPath'

    patch:
      tags:
        - Tasks
      summary: Toggle task completion status
      description: Toggles the is_completed status of a task. If completed, marks as incomplete. If incomplete, marks as completed.
      operationId: toggleTaskCompletion
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              examples:
                markedComplete:
                  summary: Task marked as complete
                  value:
                    id: 123e4567-e89b-12d3-a456-426614174000
                    user_id: 550e8400-e29b-41d4-a716-446655440000
                    title: Buy groceries
                    description: Milk, eggs, bread
                    is_completed: true
                    created_at: '2026-02-06T10:30:00Z'
                    updated_at: '2026-02-06T12:00:00Z'
                markedIncomplete:
                  summary: Task marked as incomplete
                  value:
                    id: 123e4567-e89b-12d3-a456-426614174000
                    user_id: 550e8400-e29b-41d4-a716-446655440000
                    title: Buy groceries
                    description: Milk, eggs, bread
                    is_completed: false
                    created_at: '2026-02-06T10:30:00Z'
                    updated_at: '2026-02-06T12:05:00Z'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/signin or /api/auth/signup

  parameters:
    UserIdPath:
      name: user_id
      in: path
      required: true
      description: User ID (must match authenticated user's ID)
      schema:
        type: string
        format: uuid
      example: 550e8400-e29b-41d4-a716-446655440000

    TaskIdPath:
      name: task_id
      in: path
      required: true
      description: Task ID
      schema:
        type: string
        format: uuid
      example: 123e4567-e89b-12d3-a456-426614174000

  schemas:
    TaskCreateRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title (required)
          example: Buy groceries
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Optional task description
          example: Milk, eggs, bread

    TaskUpdateRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Updated task title
          example: Buy groceries and supplies
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Updated task description
          example: Milk, eggs, bread, paper towels

    TaskResponse:
      type: object
      required:
        - id
        - user_id
        - title
        - is_completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
          example: 123e4567-e89b-12d3-a456-426614174000
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this task
          example: 550e8400-e29b-41d4-a716-446655440000
        title:
          type: string
          maxLength: 200
          description: Task title
          example: Buy groceries
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Task description (optional)
          example: Milk, eggs, bread
        is_completed:
          type: boolean
          description: Task completion status
          example: false
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp (ISO 8601)
          example: '2026-02-06T10:30:00Z'
        updated_at:
          type: string
          format: date-time
          description: Last modification timestamp (ISO 8601)
          example: '2026-02-06T10:30:00Z'

    ErrorResponse:
      type: object
      required:
        - detail
        - status_code
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: Task not found
        status_code:
          type: integer
          description: HTTP status code
          example: 404

  responses:
    UnauthorizedError:
      description: Missing or invalid JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            missingToken:
              summary: No Authorization header
              value:
                detail: Missing authentication token
                status_code: 401
            invalidToken:
              summary: Invalid or expired token
              value:
                detail: Invalid or expired token
                status_code: 401

    ForbiddenError:
      description: User attempting to access another user's tasks
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            wrongUser:
              summary: User ID mismatch
              value:
                detail: Access forbidden - user_id does not match authenticated user
                status_code: 403

    NotFoundError:
      description: Task not found or does not belong to user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            taskNotFound:
              summary: Task does not exist
              value:
                detail: Task not found
                status_code: 404

    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            emptyTitle:
              summary: Title is empty
              value:
                detail: Title cannot be empty
                status_code: 400

    UnprocessableEntityError:
      description: Request data is invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            titleTooLong:
              summary: Title exceeds maximum length
              value:
                detail: Title must not exceed 200 characters
                status_code: 422
            descriptionTooLong:
              summary: Description exceeds maximum length
              value:
                detail: Description must not exceed 2000 characters
                status_code: 422

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            serverError:
              summary: Unexpected server error
              value:
                detail: Internal server error
                status_code: 500
